# Generated by Django 5.2 on 2025-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_notificationsetting_notify_radius_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
