# Generated by Django 5.2 on 2025-04-09 07:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import utilities.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='base_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_visibility',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN_TO_MEET', 'Open to meet'), ('BUSY', 'Busy'), ('EXPLORING', 'Exploring')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROXIMITY_ALERT', 'Proximity Alert'), ('NEW_MESSAGE', 'New message'), ('PROFILE_VIEW', 'Profile_view'), ('MEETUP_INVITE', 'Meetup invite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_on_proximity', models.BooleanField(blank=True, default=True, null=True)),
                ('notify_radius_km', models.FloatField(blank=True, default=500.0, null=True)),
                ('show_email', models.BooleanField(blank=True, default=False, null=True)),
                ('dark_theme', models.BooleanField(blank=True, default=False, null=True)),
                ('meetup_periods', models.JSONField(default=list)),
                ('who_can_discover_me', models.CharField(choices=[('EVERYONE', 'Everyone'), ('VERIFIED_USER', 'Verified User'), ('ONLY_ME', 'Only Me')], default='EVERYONE', max_length=20)),
                ('show_profile_of_people_meet', models.BooleanField(blank=True, default=False, null=True)),
                ('only_verified_user_can_message', models.BooleanField(blank=True, default=False, null=True)),
                ('auto_accept_meetup_request', models.BooleanField(blank=True, default=False, null=True)),
                ('notify_on_profile_view', models.BooleanField(blank=True, default=False, null=True)),
                ('notify_on_meetup_invites', models.BooleanField(blank=True, default=False, null=True)),
                ('require_profile_completion', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
