# Generated by Django 5.2 on 2025-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='notify_on_proximity',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='notify_radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
