# Generated by Django 5.2 on 2025-04-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userpreference_meetup_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='meetup_periods',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
