# Generated by Django 5.2 on 2025-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN TO MEET', 'Open to meet'), ('BUSY', 'Busy'), ('EXPLORING', 'Exploring')], default='OPEN TO MEET', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
            preserve_default=False,
        ),
    ]
