# Generated by Django 5.2 on 2025-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_status_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('OPEN TO MEET', 'Open to meet'), ('BUSY', 'Busy'), ('EXPLORING', 'Exploring')], default='OPEN TO MEET', max_length=20),
        ),
    ]
