# Generated by Django 5.2 on 2025-04-14 13:28

import utilities.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='uid',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='id',
            field=models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
