# Generated by Django 5.2 on 2025-04-14 13:28

import utilities.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='uid',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(db_index=True, default=utilities.utils.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
